#!/usr/bin/env ruby

# This code's purpose is to serve as an example of technical debt.

TOTAL_SENTENCES_TO_SHOW = 6

def random_quote
  format_quote \
    fetch_quote(starting_sentence_index: random_matching_sentence_index)
end

def fetch_quote(starting_sentence_index:)
  @sentences.slice(starting_sentence_index, TOTAL_SENTENCES_TO_SHOW).join(" ")
end

def format_quote(quote)
  remove_line_breaks quote
end

def random_matching_sentence_index
  @matching_sentence_indexes[rand @matching_sentence_indexes.size]
end

def remove_line_breaks(text)
  text.gsub("\n", " ").chomp
end

volume = ENV["OVERLORD_TEXT"]
search_term = ARGV[0]

sentence_regex = /(?:^|\.\s*)(?:\s*)([A-Z][^.]+\.)/m

text = File.read(volume)
@sentences = text.scan(sentence_regex).flatten

@matching_sentence_indexes = []
@sentences.each_with_index do |sentence, i|
  @matching_sentence_indexes << i \
    if search_term.nil? || sentence =~ /#{search_term}/i
end
puts "Total matching_sentence_indexes: #{@matching_sentence_indexes.size}"

puts random_quote
