#!/usr/bin/env ruby

TOTAL_SENTENCES_TO_SHOW = 6

class Sentences
  SENTENCE_REGEX = /(?:^|\.\s*)(?:\s*)([A-Z][^.]+\.)/m

  include Enumerable

  def initialize(text_file)
    text = File.read text_file
    @sentences = text.scan(SENTENCE_REGEX).flatten
  end

  def raw
    @sentences
  end

  def each(&b)
    @sentences.each_with_index &b
  end

  def quote(starting_id:)
    @sentences.slice(starting_id, TOTAL_SENTENCES_TO_SHOW).join(" ")
  end
end

def random_quote
  format_quote \
    @sentences.quote(starting_id: random_matching_sentence_id)
end

def format_quote(quote)
  remove_line_breaks quote
end

def random_matching_sentence_id
  @matching_sentence_ids[rand @matching_sentence_ids.size]
end

def remove_line_breaks(text)
  text.gsub("\n", " ").chomp
end

volume = ENV["OVERLORD_TEXT"]
search_term = ARGV[0]

@sentences = Sentences.new volume

@matching_sentence_ids = []
@sentences.each do |sentence, id|
  @matching_sentence_ids << id \
    if search_term.nil? || sentence =~ /#{search_term}/i
end
puts "Total matching sentences: #{@matching_sentence_ids.size}"

puts random_quote
