#!/usr/bin/env ruby

TOTAL_SENTENCES_TO_SHOW = 6

Sentence = Struct.new(:id, :text) do
  def to_s
    text
  end
end

class Sentences
  SENTENCE_REGEX = /(?:^|\.\s*)(?:\s*)([A-Z][^.]+\.)/m

  include Enumerable

  def initialize(text_file)
    text = File.read text_file
    @sentences = text.scan(SENTENCE_REGEX).flatten

    @sentences = @sentences.each_with_index.map do |sentence, id|
      Sentence.new id, sentence
    end
  end

  def each(&b)
    @sentences.each &b
  end

  def quote(starting_id:)
    @sentences.slice(starting_id, TOTAL_SENTENCES_TO_SHOW).join(" ")
  end
end

class MatchingSentences
  def initialize(search_term, sentences)
    @search_term, @sentences = search_term, sentences
    @matching_sentences = filter_sentences
  end

  def size
    @matching_sentences.size
  end

  def raw
    @matching_sentences
  end

  private

  def filter_sentences
    return @sentences.dup unless @search_term

    @sentences.find_all do |sentence|
      sentence.text =~ /#{@search_term}/i
    end
  end
end

def random_quote
  format_quote \
    @sentences.quote(starting_id: random_matching_sentence_id)
end

def format_quote(quote)
  remove_line_breaks quote
end

def random_matching_sentence_id
  @matching_sentences.raw[rand @matching_sentences.size].id
end

def remove_line_breaks(text)
  text.gsub("\n", " ").chomp
end

volume = ENV["OVERLORD_TEXT"]
search_term = ARGV[0]

@sentences = Sentences.new volume
@matching_sentences = MatchingSentences.new search_term, @sentences

puts "Total matching sentences: #{@matching_sentences.size}"

puts random_quote
