#!/usr/bin/env ruby

def load_entries(dirs)
  dirs.flat_map { |dir| Dir.entries dir }
end

dirs = ARGV

entries = load_entries(dirs)
random_entry_index = rand(entries.size - 1)
puts entries[random_entry_index]
